### ISSUE TITLE
Lightbox remains open when saving and closing 

### ISSUE THREAD

**Issue by contaoacademy** [madeyourday/contao-rocksolid-frontend-helper#71]
When I edit content, it can happen that the lightbox remains open when I click on Save & Close.

This is not always the case. During my tests, I noticed that this happens when an image file is added or I switch to the file manager during editing. Then the automatic closing of the lightbox no longer works.

**Comment by ausi** [comment]
Should be fixed in 2.2.7

It would be great if you could verify that this fixes it in your use case as well.

**Comment by contaoacademy** [comment]
The problem seems to be only partially solved. If I change the source of an image and then click on Save & Close, the overlay remains open.

If I then continue editing, the button works again.

**Comment by ausi** [comment]
This works in a different way now in Contao 5.7.
